# Generated by Django 4.0.4 on 2022-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAlert', models.CharField(max_length=30)),
                ('descriptionAlert', models.CharField(max_length=500)),
                ('sousValeurAlert', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCompany', models.CharField(max_length=30)),
                ('nameSystem', models.CharField(max_length=30)),
                ('versionSystem', models.CharField(max_length=30)),
                ('vendeur', models.CharField(max_length=30)),
                ('typeSystem', models.CharField(max_length=30)),
            ],
        ),
    ]
